spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/demo
    username: root
    password: qwer1234!@

  jpa:
    hibernate:
      ddl-auto: update #validate #create update none validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  thymeleaf:
    prefix: classpath:templates/
    suffix: .html

  profiles:
    include: API-KEY
